# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  compile-job:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: quay.io/uuss/us8base
    # Small is struggling building release types
    resource_class: medium
    #small

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Configure code"
          command: |
            cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_FOR_DEBIAN=ON
      - run:
          name: "Build the code"
          command: |
            cmake --build build
      - run:
          name: "Install the code"
          command: |
            cmake --install build
      - run:
           name: "Test the code"
           command: |
            cd build
            ctest --verbose
      - run:
           name: "Package code"
           command: |
             cd build
             mkdir -p /tmp/artifacts
             mkdir -p /tmp/workspace
             cpack -B /tmp/artifacts TGZ
             rm -rf /tmp/artifacts/_CPack_Packages
             # Later, we're going to build a container so we duplicate some effort
             cp /tmp/artifacts/*-Linux.tar.gz /tmp/workspace/
             cp Dockerfile.deb /tmp/workspace/
             ls /tmp/workspace/
      - store_artifacts:
          path: /tmp/artifacts
  # End compile job
  deploy-job:
    docker:
      - image: cimg/base:2022.09
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Create docker image"
          command: |
            cd /tmp/workspace
            ls
            # Figure out version from app-name-MAJOR.MINOR.PATCH-Linux.deb
            debfile=$(ls *Linux.deb)
            version=$(echo ${debfile} | sed 's/uuDataPacketImportProxy-//g' | sed 's/-Linux.deb//g')
            echo ${version}
            docker build -t udatapacketimportproxy:latest -t udatapacketimportproxy:${version} -f ./Dockerfile.deb .
      - run:
          name: "Quay login"
          command: |
            docker login -u="${QUAY_ROBOT_USER}" -p="${QUAY_ROBOT_PASSWORD}" quay.io
      - run:
          name: "Upload docker image to quay"
          command: |
            docker tag udatapacketimportproxy quay.io/uuss/udatapacketimportproxy
            docker push quay.io/uuss/udatapacketimportproxy

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  compile-workflow: 
    jobs:
      - compile-job
      - deploy-job:
          requires:
            - compile-job
